### ISSUE TITLE
Make fails with wasm-ld error

### ISSUE THREAD

**Issue by chrisspen** [myers/chord_detector#4]
Running `npm run build` or simply `make` results in the error:

    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 392, in _handle_results
        task = get()
    TypeError: __init__() takes at least 3 arguments (1 given)

and the build never completes.

**Comment by chrisspen** [comment]
This was caused by an obsolete version of emscripten installed. Upgrading that fixed the issue, but `make` still fails with a different error:

    > chord_detector@1.0.5 build /home/chris/git/chord_detector
    > make; cd docs; browserify demo.js -o bundle.js

    emcc -O3 --memory-init-file 0 chord_detector_wrapper.cpp -o index.js -s EXPORTED_FUNCTIONS="['_Chromagram_constructor','_Chromagram_destructor','_Chromagram_processAudioFrame', '_Chromagram_isReady', '_Chromagram_getChromagram', '_ChordDetector_constructor', '_ChordDetector_destructor', '_ChordDetector_detectChord', '_ChordDetector_getRootNote', '_ChordDetector_getQuality', '_ChordDetector_getIntervals']" -D USE_KISS_FFT -I vendor/Chord-Detector-and-Chromagram/src -I vendor/Chord-Detector-and-Chromagram/libs/kiss_fft130 build/*.o --post-js chord_detector.js
    wasm-ld: error: build/ChordDetector.o: machine type must be wasm32 or wasm64
    wasm-ld: error: build/Chromagram.o: machine type must be wasm32 or wasm64
    wasm-ld: error: build/kiss_fft.o: machine type must be wasm32 or wasm64
    emcc: error: '/home/chris/git/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_20sbwcqu/index.wasm /tmp/emscripten_temp_20sbwcqu/chord_detector_wrapper_0.o -L/home/chris/git/emsdk/upstream/emscripten/system/local/lib build/ChordDetector.o -L/home/chris/git/emsdk/upstream/emscripten/system/lib build/Chromagram.o -L/home/chris/git/emsdk/upstream/emscripten/cache/wasm build/kiss_fft.o /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libc.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libcompiler_rt.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libc++-noexcept.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libc++abi-noexcept.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libdlmalloc.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libpthread_stub.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libc_rt_wasm.a /home/chris/git/emsdk/upstream/emscripten/cache/wasm/libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --import-memory --import-table --strip-debug --export Chromagram_constructor --export Chromagram_destructor --export Chromagram_processAudioFrame --export Chromagram_isReady --export Chromagram_getChromagram --export ChordDetector_constructor --export ChordDetector_destructor --export ChordDetector_detectChord --export ChordDetector_getRootNote --export ChordDetector_getQuality --export ChordDetector_getIntervals --export malloc --export free --export stackSave --export stackRestore --export stackAlloc --export __data_end --export __wasm_call_ctors --export __errno_location --export _ZSt18uncaught_exceptionv --export __cxa_find_matching_catch --export __cxa_is_pointer_type --export __cxa_can_catch --export setThrew -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (1)
    Makefile:2: recipe for target 'index.js' failed
    make: *** [index.js] Error 1
    Error: Cannot find module '../index.js' from '/home/chris/git/chord_detector/docs'
        at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
        at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
        at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
        at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
        at FSReqCallback.oncomplete (fs.js:167:21)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! chord_detector@1.0.5 build: `make; cd docs; browserify demo.js -o bundle.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the chord_detector@1.0.5 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by chrisspen** [comment]
The wasm-ld errors were due to bad binaries made before I had properly installed emscripten. Deleting all binaries and object files and then re-running make fixed that.

Now the error I'm getting trying to run the demo is the same as issue #3.
